# -*- coding: utf-8 -*-
"""Gemma_Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vwjB_Q2yutOHOEJXwjH0Vq006WH-sJQM
"""

from huggingface_hub import notebook_login
from transformers import AutoModelForCausalLM, AutoTokenizer

notebook_login()

# Load model directly

tokenizer = AutoTokenizer.from_pretrained("google/gemma-2b-it")
model = AutoModelForCausalLM.from_pretrained("google/gemma-2b-it")

prompt = "Write me a job description for a Machine Learning Engineer Job"

input = tokenizer.encode(prompt, return_tensors="pt")

output = model.generate(input, max_length=1000)

text = tokenizer.decode(output[0])

print(text)
